Repository GSG-G13/Booky, pull requests merged in 2023-03, with the labels that each got.

#9 Header Section
  header.avif
  index.html
  style.css
Labels: approved

#10 Book Show API
  .gitignore
  book-open-line.svg
  header.avif
  index.html
  script.js
  style.css
Labels: done

#11 Quotes Section
  index.html
  script.js
  style.css
Labels: approved

#12 7 seemore btn
  __test__/index.js
  functions.js
  index.html
  script.js
  style.css
Labels: approved

#15 Loading Animation
  index.html
  script.js
  style.css
Labels: approved

#17 README File
  README.md
Labels: approved

#19 Fixing Live Link
  README.md
Labels: awaiting-review

#21 20 fixing live link 2
  README.md
  index.html
Labels: approved
